# Generated by Django 5.1.6 on 2025-05-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the exercise.', max_length=30)),
                ('instruction', models.CharField(help_text='The instruction to be displayed.', max_length=300)),
                ('assert_output', models.CharField(help_text='Output (code) to be asserted.', max_length=1000)),
                ('language', models.CharField(choices=[('C#', 'Csharp'), ('Py', 'Python'), ('SQL', 'Structured Query Language (SQL)')], default='Py', help_text='Programming language of the exercise.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(choices=[(1, 'Shit'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Rizz')])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadania.exercise')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('code_file', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('solution_text', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Date Added')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadania.exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
