# Generated by Django 5.2 on 2025-05-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jezyki', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
