# Generated by Django 5.2 on 2025-05-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jezyki', '0003_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
